remote_theme: just-the-docs/just-the-docs

aux_links:
  "PygamePlus on GitHub":
    - "https://github.com/mrdevet/PygamePlus"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2022 Casey Devet. Distributed by an <a href=\"https://github.com/mrdevet/PygamePlus/blob/master/LICENSE\">MIT license.</a>"

collections:
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  classes:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tutorials:
      name: "Tutorials"
    classes:
      name: "Classes"